name: pacific_bank
description: "Pacific Bank WebView"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  rename_app: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/launch-icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon.png"
  android: true
  android_12:
    color: "#ffffff"
    image: "assets/icons/splash-icon.png"
